version: "3.9"

services:
  # api-gateway:
  #   build: ./services/api-gateway
  #   container_name: api-gateway
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - auth-service
  #     - characters-service
  #     - game-engine
  #   environment:
  #     AUTH_PUBLIC_KEY_PATH: /keys/public.pem
  #   volumes:
  #     - ./infra/keys:/keys
  #   networks:
  #     - backend

  auth-service:
    build: ./services/auth
    container_name: auth-service
    ports:
      - 4000:3000
    environment:
      DATABASE_URL: postgres://auth:auth@auth-db:5432/auth
      JWT_PRIVATE_KEY_PATH: /keys/private.pem
      JWT_PUBLIC_KEY_PATH: /keys/public.pem
    volumes:
      - ./infra/keys:/keys
      - ./services/auth/src:/app/src
    depends_on:
      - auth-db
    networks:
      - backend
    command:
      npm run start:dev

  characters-service:
    build: ./services/characters
    container_name: characters-service
    ports:
      - 5000:3000
    environment:
      DATABASE_URL: postgres://characters:characters@characters-db:5432/characters
      GAME_ENGINE_URL: http://game-engine:3000
      AUTH_PUBLIC_KEY_PATH: /keys/public.pem
    volumes:
      - ./infra/keys:/keys
      - ./services/characters/src:/app/src
    depends_on:
      - characters-db
      # - game-engine
    networks:
      - backend
    command:
      npm run start:dev

  # game-engine:
  #   build: ./services/game-engine
  #   container_name: game-engine
  #   environment:
  #     NODE_ENV: production
  #   networks:
  #     - backend

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - backend

  characters-db:
    image: postgres:16
    container_name: characters-db
    environment:
      POSTGRES_DB: characters
      POSTGRES_USER: characters
      POSTGRES_PASSWORD: characters
    volumes:
      - characters-db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  auth-db-data:
  characters-db-data:

networks:
  backend:
    driver: bridge
